/* ── Central product catalog ─────────────────────────────────────────────────
   Single source of truth for every product in the app.
   All homepage components and the products/detail pages import from here.
   IDs 1-6   : tech products shown in the /products listing
   IDs 7-14  : Home & outdoor (CategoryGrid + detail pages)
   IDs 15-20 : Clothing & accessories (RecommendedItems + detail pages)
   IDs 21-23 : Extra electronics (CategoryGrid / DealsAndOffers + detail pages)
──────────────────────────────────────────────────────────────────────────── */

export interface Product {
  id: number;
  title: string;
  brand: string;
  category: string;
  subCategory: string;
  src: string;
  alt: string;
  price: number;
  originalPrice: number;
  rating: number;
  orders: number;
  description: string;
}

export const PRODUCTS: Product[] = [

  /* ── Electronics ── */
  {
    id: 1,
    title: "Canon Camera EOS 2000, Black 10x zoom",
    brand: "Canon",
    category: "Electronics",
    subCategory: "Cameras",
    src: "/assets/260c7a4b2c0a4a3071479d3ea04dbef308c19301.png",
    alt: "Canon EOS 2000D DSLR camera with 18-55mm kit lens",
    price: 998.00,
    originalPrice: 1128.00,
    rating: 4,
    orders: 154,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: 2,
    title: "Huawei MateBook Laptop — Space Gray, 512 GB SSD",
    brand: "Huawei",
    category: "Electronics",
    subCategory: "Laptops",
    src: "/assets/f16c3be367d46067797d63f72c5d238bab2c834f.png",
    alt: "Huawei MateBook laptop top-down view in space gray",
    price: 998.00,
    originalPrice: 1128.00,
    rating: 4,
    orders: 154,
    description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: 3,
    title: "Amazfit GTS 2 Smart Watch — Silver Case, Gray Band",
    brand: "Amazfit",
    category: "Mobile accessory",
    subCategory: "Smart Watches",
    src: "/assets/9d00665ee4b654e7de1ac596c31da4b9f1994793.png",
    alt: "Amazfit GTS 2 smart watch silver case with gray silicone band",
    price: 998.00,
    originalPrice: 1128.00,
    rating: 4,
    orders: 154,
    description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: 4,
    title: "Xiaomi Mi Pad 5 Tablet — Matte Black, 256 GB",
    brand: "Xiaomi",
    category: "Smartphones",
    subCategory: "Tablets",
    src: "/assets/d5df9baf5b845d5b649289426578b53ebaef4c65.png",
    alt: "Xiaomi Mi Pad 5 tablet in matte black",
    price: 998.00,
    originalPrice: 1128.00,
    rating: 4,
    orders: 154,
    description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: 5,
    title: "Apple iPhone 12 — PRODUCT RED, 128 GB",
    brand: "Apple",
    category: "Smartphones",
    subCategory: "iPhones",
    src: "/assets/01ad73c0a2d288ce5bd52ddfac2945120df5102b.png",
    alt: "Apple iPhone 12 PRODUCT RED",
    price: 998.00,
    originalPrice: 1128.00,
    rating: 4,
    orders: 154,
    description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  {
    id: 6,
    title: "Xiaomi Wireless Over-Ear Headphones — White",
    brand: "Xiaomi",
    category: "Mobile accessory",
    subCategory: "Headphones",
    src: "/assets/37220adadb935c4b51e951193ddd1064f61e7b77.png",
    alt: "Xiaomi wireless over-ear headphones in white with gold accent ring",
    price: 998.00,
    originalPrice: 1128.00,
    rating: 4,
    orders: 154,
    description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },

  /* ── Home & outdoor ── */
  {
    id: 7,
    title: "Beige Accent Armchair — Soft Microfibre",
    brand: "IKEA",
    category: "Home & outdoor",
    subCategory: "Soft chairs",
    src: "/assets/4450cf999324f0c42ef6175c1e8fd94fcdaea111.png",
    alt: "Beige accent armchair",
    price: 245.00,
    originalPrice: 290.00,
    rating: 5,
    orders: 87,
    description: "Comfortable accent armchair upholstered in soft microfibre. Features solid wood legs and a high back for full support.",
  },
  {
    id: 8,
    title: "Inflatable Air Sofa — 2-Seater, Light Grey",
    brand: "HomePro",
    category: "Home & outdoor",
    subCategory: "Sofa & chair",
    src: "/assets/de013dbdda0ec19b2f735896bd129bb83cae628f.png",
    alt: "Inflatable air sofa in light grey",
    price: 79.00,
    originalPrice: 99.00,
    rating: 4,
    orders: 210,
    description: "Lightweight inflatable sofa ideal for outdoor use, camping, or extra seating at home. Quick to inflate and deflate.",
  },
  {
    id: 9,
    title: "Dracaena Indoor Plant — Taupe Ceramic Pot",
    brand: "GreenLife",
    category: "Home & outdoor",
    subCategory: "Plants",
    src: "/assets/37fcfe74e17c636fb7cc35743a81e426e6e52604.png",
    alt: "Dracaena plant in taupe ceramic pot",
    price: 34.00,
    originalPrice: 42.00,
    rating: 5,
    orders: 312,
    description: "Low-maintenance Dracaena marginata in a stylish taupe ceramic pot. Great for improving indoor air quality.",
  },
  {
    id: 10,
    title: "Stone-Base Table Lamp — Linen Shade, Warm White",
    brand: "Lumina",
    category: "Home & outdoor",
    subCategory: "Table lamps",
    src: "/assets/e7609aa3afe3483e736054358d53f2f8797b4546.png",
    alt: "Stone-base table lamp with linen shade",
    price: 58.00,
    originalPrice: 72.00,
    rating: 4,
    orders: 65,
    description: "Elegant table lamp with a natural stone base and beige linen shade. Creates warm ambient lighting for any room.",
  },
  {
    id: 11,
    title: "Tan Leather Magazine Rack — 3-Slot Organiser",
    brand: "Artisan",
    category: "Home & outdoor",
    subCategory: "Home organiser",
    src: "/assets/a3565d31ff34eb5b476f6a97fc3fde243beb9597.jpg",
    alt: "Tan leather magazine rack with metal frame",
    price: 42.00,
    originalPrice: 55.00,
    rating: 4,
    orders: 43,
    description: "Handcrafted genuine leather magazine rack with three wide slots. Sturdy metal frame keeps it upright on any surface.",
  },
  {
    id: 12,
    title: "Cold-Press Slow Juicer — 100 W, 1.5 L",
    brand: "NutriPro",
    category: "Home & outdoor",
    subCategory: "Kitchen mixer",
    src: "/assets/67ecd6b2d628afe6f0f52ecee5cf9460f0d0d69d.png",
    alt: "Cold-press slow juicer with fresh fruits",
    price: 89.00,
    originalPrice: 115.00,
    rating: 5,
    orders: 176,
    description: "Slow-speed cold-press juicer preserves enzymes and vitamins. Wide 80 mm chute accepts whole fruits with minimal prep.",
  },
  {
    id: 13,
    title: "Bosch Tassimo Vivy 2 Coffee Machine — Black",
    brand: "Bosch",
    category: "Home & outdoor",
    subCategory: "Coffee maker",
    src: "/assets/649567d50c25ac335a1e2cc7d8d3584a3592fbbf.png",
    alt: "Bosch Tassimo Vivy 2 coffee machine in black",
    price: 69.00,
    originalPrice: 89.00,
    rating: 4,
    orders: 234,
    description: "Single-serve coffee machine with T DISC technology. Brews coffee, cappuccino, latte and more at the touch of a button.",
  },
  {
    id: 14,
    title: "Terracotta Clay Cooking Pot — 3 L Capacity",
    brand: "CeramiCook",
    category: "Home & outdoor",
    subCategory: "Cooking pots",
    src: "/assets/a542fa1c1ebac249f8cba9ff49b0a3c5c89dfbc7.png",
    alt: "Terracotta clay cooking pot",
    price: 27.00,
    originalPrice: 35.00,
    rating: 5,
    orders: 98,
    description: "Traditional terracotta clay pot ideal for slow cooking, casseroles, and stews. Retains heat evenly for rich flavours.",
  },

  /* ── Clothing & accessories ── */
  {
    id: 15,
    title: "H&M Polo Shirt — Heathered Teal, Men's",
    brand: "H&M",
    category: "Clothing",
    subCategory: "T-shirts",
    src: "/assets/66ac8758b171e503e38e7b8c0a5fa03996d5d467.png",
    alt: "H&M heathered teal polo shirt",
    price: 10.30,
    originalPrice: 14.00,
    rating: 4,
    orders: 520,
    description: "Classic short-sleeve polo shirt in breathable cotton piqué. Available in multiple colours and sizes from S to XXL.",
  },
  {
    id: 16,
    title: "Hooded Bomber Jacket — Tan Faux-Fur Trim",
    brand: "Zara",
    category: "Clothing",
    subCategory: "Jackets",
    src: "/assets/a14ab6ac18aa7b0da8ec069e90fab9443221e2f2.jpg",
    alt: "Tan hooded bomber jacket with faux-fur trim hood",
    price: 39.90,
    originalPrice: 55.00,
    rating: 4,
    orders: 183,
    description: "Oversized bomber jacket with a detachable faux-fur trim hood. Quilted lining keeps you warm in cold weather.",
  },
  {
    id: 17,
    title: "Tailored Two-Button Blazer — Cobalt Blue",
    brand: "Marks & Spencer",
    category: "Clothing",
    subCategory: "Blazers",
    src: "/assets/b720dd65fcc6274edfb7e97f682185ec460b6d4f.png",
    alt: "Cobalt blue tailored men's blazer",
    price: 59.50,
    originalPrice: 79.00,
    rating: 5,
    orders: 97,
    description: "Slim-fit two-button blazer in vibrant cobalt blue. Perfect for smart-casual occasions. Includes chest and side pockets.",
  },
  {
    id: 18,
    title: "Slim Genuine Leather Bifold Wallet — Blue",
    brand: "Fossil",
    category: "Clothing",
    subCategory: "Accessories",
    src: "/assets/3e0d988a895e1e83befccaeafc962783f0de80c5.png",
    alt: "Blue leather bifold wallet",
    price: 8.99,
    originalPrice: 12.00,
    rating: 4,
    orders: 641,
    description: "Slim bifold wallet crafted from genuine full-grain leather. Features 6 card slots, 2 bill compartments, and an ID window.",
  },
  {
    id: 19,
    title: "Denim Drawstring Backpack — Light Blue",
    brand: "Levi's",
    category: "Clothing",
    subCategory: "Bags",
    src: "/assets/deea14d78e68b15c28eb29234224b8b2f71d5eb5.png",
    alt: "Light blue denim drawstring canvas bag",
    price: 14.50,
    originalPrice: 20.00,
    rating: 4,
    orders: 258,
    description: "Casual drawstring backpack in durable denim. Spacious main compartment with an inner pocket. Lightweight and washable.",
  },
  {
    id: 20,
    title: "Classic Cut-Off Denim Shorts — Blue, Relaxed Fit",
    brand: "Levi's",
    category: "Clothing",
    subCategory: "Shorts",
    src: "/assets/8ef134a2fbdc1fec81bd703736016e62fddab16b.png",
    alt: "Classic blue denim cut-off shorts",
    price: 12.00,
    originalPrice: 18.00,
    rating: 4,
    orders: 374,
    description: "Relaxed cut-off denim shorts with a raw hem. Made from 100% cotton. Available in waist sizes 28 to 36.",
  },

  /* ── Extra electronics ── */
  {
    id: 21,
    title: "Xiaomi Mi 9 Smartphone — Matte Black, 6 GB RAM",
    brand: "Xiaomi",
    category: "Smartphones",
    subCategory: "Smartphones",
    src: "/assets/ebb1aca726e944afe4e9b344a9d08d2cdf13f6ac.png",
    alt: "Xiaomi Mi 9 matte black smartphone",
    price: 89.00,
    originalPrice: 120.00,
    rating: 4,
    orders: 289,
    description: "Flagship Xiaomi Mi 9 with 6 GB RAM and 128 GB storage. Triple rear cameras with 48 MP main sensor and fast charging.",
  },
  {
    id: 22,
    title: "Viomi Smart Electric Kettle — Matte Black, 1.5 L",
    brand: "Viomi",
    category: "Electronics",
    subCategory: "Electric kettles",
    src: "/assets/7984cd83b66e289400004efec8d3c212c576efd7.png",
    alt: "Viomi matte black electric kettle",
    price: 34.00,
    originalPrice: 45.00,
    rating: 4,
    orders: 312,
    description: "Smart electric kettle with temperature control and keep-warm function. 1500 W rapid boil. Connects via Mi Home app.",
  },
  {
    id: 23,
    title: "Pro Gaming Wired Headset — Red & Black",
    brand: "HyperX",
    category: "Mobile accessory",
    subCategory: "Gaming headsets",
    src: "/assets/fd01d17a7844418a11051c24070081697c1e9a58.png",
    alt: "Wired gaming headset in red and black",
    price: 49.00,
    originalPrice: 65.00,
    rating: 4,
    orders: 421,
    description: "Over-ear gaming headset with 7.1 virtual surround sound. Noise-cancelling mic, memory foam ear cushions, braided cable.",
  },
];
